function data = import_daily(filename, startRow, endRow)
    delimiter = ' ';
    if nargin<=2
        startRow = 2;
        endRow = inf;
    end
    formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

    fileID = fopen(filename,'r');
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
        'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,...
        NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, ...
            'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,...
            NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    fclose(fileID);

    data = table(dataArray{1:end-1}, 'VariableNames', ...
        {'Year','MonthOfYear','DayOfMonth','DayOfYear','DayOfCentury',...
        'AirPressurehPa','AirTemperatureC','AirTemperatureHygroClipC',...
        'RelativeHumidity_wrtWater','RelativeHumidity','WindSpeedms',...
        'WindDirectiond','ShortwaveRadiationDownWm2','ShortwaveRadiationDown_CorWm2',...
        'ShortwaveRadiationUpWm2','ShortwaveRadiationUp_CorWm2',...
        'Albedo_theta70d','LongwaveRadiationDownWm2','LongwaveRadiationUpWm2',...
        'CloudCover','SurfaceTemperatureC','HeightSensorBoomm','HeightStakesm',...
        'DepthPressureTransducerm','DepthPressureTransducer_Corm',...
        'AblationPressureTransducermm','IceTemperature1C','IceTemperature2C',...
        'IceTemperature3C','IceTemperature4C','IceTemperature5C','IceTemperature6C',...
        'IceTemperature7C','IceTemperature8C','TiltToEastd','TiltToNorthd',...
        'LatitudeGPS_HDOP1ddmm','LongitudeGPS_HDOP1ddmm','ElevationGPS_HDOP1m',...
        'HorDilOfPrecGPS_HDOP1','LoggerTemperatureC','FanCurrentmA','BatteryVoltageV'});
end
